name: Sync Cameras
on:
  schedule:
    - cron: '0 8 * * *' # Runs daily at 8:00 AM UTC
  workflow_dispatch: # Allows you to click a button to run it manually

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install requests
        
      - name: Fetch Data
        run: python fetch.py
        
      - name: Save and Push to GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add cameras.geojson
          git commit -m "Daily camera sync" || exit 0
          git push
